[package]
name = "station-meteo"
version = "0.1.0"
authors = ["GrimalDev <bapt.grimaldi@gmail.com>", "ratataque"]
edition = "2018"

[dependencies]
ruduino = {  git = "https://github.com/avr-rust/ruduino", branch = "master" }

[profile.release]
opt-level = 'z'
lto = true
strip = true
