[build]
target = "avr-unknown-gnu-atmega328"

[unstable]
build-std = ["core"]

[target.avr-unknown-gnu-atmega328]
runner = "true"
rustflags = [
    "-C", "link-arg=-lc",
]

[env]
AVR_CPU_FREQUENCY_HZ = "16_000_000"
